### PR TITLE
Rust concurrency talk

### PR DESCRIPTION
**Pull request by cmgriffing**

### CODE REVIEW

**Comment by cmgriffing** [comment]
I had to make some changes to fix submodule issues that were preventing gh-pages from compiling on my fork.

Tested and working here: https://cmgriffing.github.io/meetups/2016-08-8/rust-concurrency-talk/html/

**Comment by ranweiler** [comment]
Thanks @cmgriffing!

One question: is there a reasonable way to _not_ include all of reveal.js, but just have a mechanism that will allow a user to easily pull it in locally? It contains some binary data (font files) and is a bit large generally. Not a big deal, but if we can avoid vendoring it, I'd prefer to do that.

**Comment by cmgriffing** [comment]
Sure thing. I was just under the impression that this meetups repo was going to be used in seattle.rs via gh-pages functionality.

I'm just going to put a "vendor.sh" file in the "rust-concurrency-talk" folder.

If you prefer a different convention let me know, but it might be useful have a set convention for non-rust dependencies that a simple script could use to compile a gh-pages branch later.

Edit: Sorry still a bit new to Rust, but it looks like I should be able to do it inside the build script as defined by cargo(http://doc.crates.io/build-script.html). Just not sure you would want to build all the rust packages when you just want to deploy to gh-pages though. So, the question comes down to whether future gh-pages compilation is actually a goal of this repo. If not that is fine, and I will use the build script.

**Comment by ranweiler** [comment]
@cmgriffing, I was totally failing to account for gh-pages! With that in mind, tracking the build output (including reveal.js) is definitely the way to go.

If you want to stick a build script in there, that'd be great, but I'll merge this in either way.

**Comment by cmgriffing** [comment]
With the reveal.js lib there, I don't think an extra build step is needed. I just updated the README with compilation instructions containing  a link to tango as well as the command to use pandoc to convert the markdown to html.

**Comment by ranweiler** [comment]
Agreed. Thanks for all the time you put into this!

**Pull request merged**
